[config]
schemaVersion = "0.0.1"

[package]
namespace = "Jiemas"
name = "EnlightenedJi"
versionNumber = "1.0.0"
description = "Mods Ji to be harder"
websiteUrl = "https://github.com/Jiemas/nine-sols-modding"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"

[build]
icon = "./428px-JiP_young.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
